server:
  shutdown: graceful

spring:
  application:
    name: melosys-skattehendelser
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_JDBC_URL}
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
  lifecycle:
    timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=15m

melosys:
  kafka:
    brokers: ${KAFKA_BROKERS}
    security:
      keystorePath: ${KAFKA_KEYSTORE_PATH:/dev/zero}
      truststorePath: ${KAFKA_TRUSTSTORE_PATH:/dev/zero}
      credstorePassword: ${KAFKA_CREDSTORE_PASSWORD:pwd}
    producer:
      topic: ${KAFKA_SKATTEHENDELSE_TOPIC}
    consumer:
      topic: ${KAFKA_VEDTAK_TOPIC}
      groupId: teammelosys-skattehendelser-consumer

sigrun:
  rest:
    url: ${SIGRUN_REST_URL}

cron:
  job:
    prosesser-skatt-hendelser: ${CRON_JOB_PROSESSER_SKATTE_HENDELSER:0 0 2 * * *} # Kjør kl 02:00 hver dag

admin:
  api-key: ${ADMIN_API_KEY}

app:
  dry-run-publisering: ${DRY_RUN_PUBLISERING:false}

skatt:
  fetcher:
    batch-size: ${SKATT_FETCHER_BATCH_SIZE:500}
    start-dato: ${SKATT_START_DATO:2023-01-01}

no.nav.security.jwt.client.registration:
  sigrun:
    token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
    grant-type: client_credentials
    scope: api://${CLUSTER_SIGRUN}.team-inntekt.${APP_NAME_SIGRUN}/.default
    authentication:
      client-id: ${AZURE_APP_CLIENT_ID}
      client-secret: ${AZURE_APP_CLIENT_SECRET}
      client-auth-method: client_secret_basic

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,caches,metrics
      base-path: /internal
  health:
    diskspace:
      enabled: false
  metrics:
    enable:
      cache: true