spring:
  application:
    name: melosys-skattehendelser
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_JDBC_URL}
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none

melosys:
  kafka:
    brokers: ${KAFKA_BROKERS:localhost:29092}
    security:
      keystorePath: ${KAFKA_KEYSTORE_PATH:/dev/zero}
      truststorePath: ${KAFKA_TRUSTSTORE_PATH:/dev/zero}
      credstorePassword: ${KAFKA_CREDSTORE_PASSWORD:pwd}
    producer:
      topic: ${KAFKA_SKATTEHENDELSE_TOPIC:teammelosys.skattehendelser.v1}
    consumer:
      topic: ${KAFKA_VEDTAK_TOPIC:teammelosys.melosys-hendelser.v1-q2}
      groupId: teammelosys-vedtakMelding-consumer

sigrun:
  rest:
    url: temp

no.nav.security.jwt.client.registration:
  sigrun:
    token-endpoint-url: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
    grant-type: client_credentials
    scope: api://prod-fss.team-inntekt.sigrun/.default
    authentication:
      client-id: ${AZURE_APP_CLIENT_ID}
      client-secret: ${AZURE_APP_CLIENT_SECRET}
      client-auth-method: client_secret_basic

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /internal