spring:
  application:
    name: melosys-skattehendelser
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none

melosys:
  kafka:
    brokers: ${KAFKA_BROKERS:localhost:9092}
    security:
      keystorePath: ${KAFKA_KEYSTORE_PATH:/dev/zero}
      truststorePath: ${KAFKA_TRUSTSTORE_PATH:/dev/zero}
      credstorePassword: ${KAFKA_CREDSTORE_PASSWORD:pwd}
    producer:
      topic: ${KAFKA_SKATTEHENDELSE_TOPIC:teammelosys.skattehendelser.v1}
    consumer:
      topic: ${KAFKA_VEDTAK_TOPIC:teammelosys.melosys.vedtak.v1}
      groupId: teammelosys-vedtakMelding-consumer

sigrun:
  rest:
    url: temp