apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app_name}}
  namespace: {{namespace}}
  labels:
    team: teammelosys
spec:
  startup:
    failureThreshold: 10
    initialDelay: 55
    path: /internal/health
    timeout: 5
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: {{database_tier}}
        diskAutoresize: true
        databases:
          - name: {{database_name}}
            envVarPrefix: DB
        flags:
          - name: timezone
            value: "Europe/Oslo"
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/health
    initialDelay: 60
    timeout: 5
  readiness:
    path: /internal/health
    initialDelay: 55
    timeout: 5
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      allowAllUsers: false
      claims:
        groups:
          - id: {{group_melosys_innlogging}}
  accessPolicy:
    outbound:
      external:
        - host: "melosys-unleash-api.nav.cloud.nais.io"
        - host: "team-inntekt-proxy.dev-fss-pub.nais.io"
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - {{ingress}}
  kafka:
    pool: {{kafka_pool}}
  env:
    - name: KAFKA_SKATTEHENDELSE_TOPIC
      value: {{kafka_topic_name_skattehendelse}}
    - name: KAFKA_VEDTAK_TOPIC
      value: {{kafka_topic_name_hendelse}}
    - name: CLUSTER_SIGRUN
      value: {{cluster_sigrun}}
    - name: APP_NAME_SIGRUN
      value: {{app_name_sigrun}}

